---
title: Brilliant Cassowary's Coffee Research
subtitle: "Preregistration of analyses"
author: 
  - "Nidhi Soma (ns848)"
  - "Joice Chen (jc3528)"
  - "Jinpeng Li (jl3496)"
  - "Stephen Syl-Akinwale (sis33)"
editor: 
  markdown: 
    wrap: sentence
---



# Inserting the dataset on Coffee
```{r}
library(tidyverse)
coffee_df<-read_csv("data/GACTT_RESULTS_ANONYMIZED_v2.csv")

```

# Hypothesis 1

**Younger people 18 - 25 prefer their coffee with lighter roasts. **

Analysis: Run a linear (or logistic, if that fits better) regression where we input each age category as a discrete variable and output a prediction of the probability of preferring lighter roasts (refer to HW6 ex 2). We consider lighter roasts to be Light, Nordic, or Medium according to the roast_level column. The first age-group, which is the 18-25 age group, will be the reference variable, so we can see if the coefficents for the other age groups is not 0, so they factor into a lighter roast level preference.
.

# Hypothesis 2

**People who have higher levels of education are less likely to prefer their coffee with added sweetener. **

Analysis: Run a linear regression where we input education level as a discrete variable and output a prediction of the probability of answering TRUE to the variables starting with sugar_sweetener_added. The first group "less than high school" degree will be used as the reference variable.