---
title: Coffee Preferences
author: Brilliant Cassowary <br> Jinpeng Li, Joice Chen, Nidhi Soma, Stephen Syl-Akinwale 
date: today
format:
  revealjs: 
    theme: simple
execute:
  echo: false
---

## Introduce the topic and motivation

Coffee is one of the most popular choices for students across campus. We wanted to see if there were any trends we could analyze about coffee preferences at large.

General research question: How does coffee preference and consumption habits differ by demographic attributes such as age, gender, education level, race, and political identity?

## Introduce the data

- Data collected from James Hoffman's "The Great American Coffee Taste Test"

- Surveyed almost 4000 respondents about their coffee preferences
- Participants were required weighing scale,a way of heating hot water, 
and cups that can accommodate about 250 mLs or eight ounces
- Coffee A - Light roast, Washed, Coffee B - Medium Roast, Coffee C - Dark roast, Coffee D - Fermented, Natural, Fruity

## Highlights from EDA

When you click the **Render** button a presentation will be generated that includes both content and the output of embedded code. You can embed code like this:

```{r}
1 + 1
```

## Inference/modeling/other analysis

Your results here

## Inference/modeling/other analysis

Your results here

## Conclusions + future work
